spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8

  data:
    mongodb:
      uri: mongodb://localhost:27017/rtsup_dev

  boot:
    admin:
      url: http://localhost:8080
  jackson:
    serialization:
       indent-output: true
